name: Python CI/CD Workflow

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Python 3.10
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Create and activate virtual environment
              run: |
                  python -m venv venv
                  source venv/bin/activate

            - name: Install dependencies
              run: |
                  pip install --upgrade pip
                  pip install -r requirements.txt

    build-and-push-docker:
        needs: build-and-test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: python-sample-app-action/python-sample-app-actions:latest

    deploy:
        needs: build-and-push-docker
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to Server
              run: echo "Deploying the application now"
